# Generated by Django 4.1.2 on 2022-10-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='my_last_name',
            new_name='my_age',
        ),
        migrations.AddField(
            model_name='about',
            name='my_lastName',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
