# Generated by Django 4.1.2 on 2022-10-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_rename_my_last_name_about_my_age_about_my_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='my_Award',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='my_happyPerson',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='my_proEnd',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
