# Generated by Django 4.1.2 on 2022-10-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_about_my_award_about_my_happyperson_about_my_proend'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='my_photo',
            field=models.ImageField(default=1, upload_to='photo/'),
            preserve_default=False,
        ),
    ]
