# Generated by Django 4.1.2 on 2022-10-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_about_my_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='my_photo',
            field=models.FileField(upload_to='photo/'),
        ),
    ]
