# Generated by Django 4.1.2 on 2022-10-27 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_alter_about_my_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='my_photo',
        ),
    ]
