# Generated by Django 4.1.2 on 2022-10-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_remove_about_my_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='my_photo',
            field=models.FileField(default=1, upload_to='photo/'),
            preserve_default=False,
        ),
    ]
