# Generated by Django 4.1.2 on 2022-10-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0010_remove_contact_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Контакты', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AddField(
            model_name='contact',
            name='number',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
