# Generated by Django 4.1.2 on 2022-10-28 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0011_alter_contact_options_contact_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={},
        ),
    ]
