# Generated by Django 4.1.2 on 2022-10-28 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0012_alter_contact_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='number',
        ),
    ]
